# src/llm/generate_cards.py
### Modules importation
from __future__ import annotations
import json
import re
import requests
from typing import Any, Dict, List

from .prompts import FLASHCARDS_PROMPT

### ------------------------------- Class ------------------------------- ###
### Class : OllamaError
class OllamaError(RuntimeError):
    """
    Custom exception raised for Ollama-related errors.

    This exception is used to explicitly signal failures
    occurring during interactions with the Ollama API.

    :return RuntimeError: Specialized runtime error for Ollama calls
    """
    pass

### ------------------------------ Helpers ------------------------------ ###
### Helper : _extract_json()
def _extract_json(text: str) -> Dict[str, Any]:
    """
    Extracts a valid JSON object from a string.

    This function is designed to handle outputs from Qwen,
    which can sometimes :
    - return valid JSON directly,
    - or surround the JSON with explanatory text (markdown, sentences, etc.).

    The function first attempts to parse the entire string directly.
    If this fails, it searches for the first JSON block delimited by `{` and `}`
    and attempts to parse it.

    :param str text: Raw text returned by the language model, assumed to contain a JSON object
    :return Dict[str, Any]: Python dictionary corresponding to the extracted JSON.
    """
    try:
        ### Direct parsing attempt
        return json.loads(text)
    except json.JSONDecodeError:
        ### Searching for a JSON block included in text
        start = text.find("{")
        end = text.rfind("}")

        ### Verify that the terminals are valid and correctly ordered
        if start != -1 and end != -1 and end > start:
            return json.loads(text[start: end + 1])

        ### No usable JSON found : propagate the error
        raise

### Helper : _fallback_title()
def _fallback_title(source_text: str, max_words: int = 8) -> str:
    """
    Generate a fallback title from a source text.

    It extracts the first words of the source text
    to create a short, human-readable title when no explicit
    title is provided.

    :param str source_text: Original source text
    :param int max_words: Maximum number of words to include
    :return str: Generated fallback title
    """
    ### Normalize whitespace
    txt = re.sub(r"\s+", " ", (source_text or "").strip())

    ### Extract the first words
    words = txt.split(" ")
    return " ".join(words[:max_words]).strip() or "Cours"

### Helper : _clean_title()
def _clean_title(t: str, max_len: int = 80) -> str:
    """
    Normalize and truncate a title string.

    :param str t: Raw title string
    :param int max_len: Maximum allowed title length
    :return str: Cleaned and truncated title
    """
    ### Normalize whitespace
    t = re.sub(r"\s+", " ", (t or "")).strip()

    ### Enforce maximum length
    return t[:max_len]

### ----------------------------- Functions ----------------------------- ###
### Function : ollama_chat()
def ollama_chat(
    messages: List[Dict[str, str]],
    model: str = "qwen2.5:7b-instruct",
    host: str = "http://localhost:11434",
    timeout_s: int = 120,
) -> str:
    """
    Sends a conversation request to an Ollama server and returns
    the model's text response.

    This function encapsulates an HTTP call to Ollama's `/api/chat` API, using a message
    format compatible with chat-type models (role/content).
    
    :param List[Dict[str, str]] messages: 
        Conversation history in the format expected by Ollama
        Each message must contain at least the following keys :
        - "role" : role of the sender ("system," "user," "assistant")
        - "content" : textual content of the message
    :param str model:
        Name of the Ollama model to use (default is “qwen2.5:7b-instruct”)
    :param str host:
        Ollama server URL (default “http://localhost:11434”)
    :param int, optional timeout_s:
        Maximum wait time for the HTTP request, in seconds
    :return str:
        Text content of the response generated by the model
        Returns an empty string if no content is present
    :raises OllamaError:
        If the Ollama server returns an HTTP code other than 200
    """
    ### Building the chat endpoint URL
    url = f"{host}/api/chat"

    ### Payload compliant with the Ollama API
    payload = {
        "model": model,
        "stream": False,
        "messages": messages,
    }

    ### Sending the POST request to the Ollama server
    r = requests.post(url, json=payload, timeout=timeout_s)

    ### Explicit HTTP error handling
    if r.status_code != 200:
        raise OllamaError(f"Ollama HTTP {r.status_code}: {r.text[:300]}")

    ### Parsing the JSON response
    data = r.json()
    ### format : {"message": {"content": "..."}}
    ### Securing access to nested keys
    return (data.get("message", {}) or {}).get("content", "") or ""

### Function : generate_cards()
def generate_cards(
    source_text: str,
    n: int = 8,
    model: str = "qwen2.5:7b-instruct",
) -> Dict[str, Any]:
    """
    Generates a set of flashcards from a source text
    using a language model via Ollama.

    This function :
    1. Constructs a structured prompt explicitly requesting a
       response in JSON format.
    2. Queries the Qwen model with a strong constraint
       on the output format (JSON only).
    3. Parses and returns the generated JSON structure.

    :param str source_text: Input text from which flashcards should be created
    :param int, optional n: Number of flashcards to generate (default 8)
    :param str, optional model: Model name Ollama used for generation
    :return Dict[str, Any]:
        JSON structure containing the generated flashcards
        The exact format depends on the `FLASHCARDS_PROMPT` prompt
    :raises json.JSONDecodeError:
        If the model's response does not contain any valid, usable JSON

    """
    ### Building the prompt from the source text
    prompt = FLASHCARDS_PROMPT.format(n=int(n), source_text=source_text.strip())

    ### Call to the model via Ollama with strict format constraint
    content = ollama_chat(
        messages=[
            {"role": "system", "content": "Tu réponds uniquement avec du JSON valide."},
            {"role": "user", "content": prompt},
        ],
        model=model,
    )

    ### Extracting and parsing the JSON returned by the model
    data = _extract_json(content)

    ### We secure the structure
    if not isinstance(data, dict):
        data = {"cards": []}

    ### Title
    title = data.get("title")

    if isinstance(title, list) and title:
        title = title[0]
        if isinstance(title, dict) and title:
            title = next(iter(title.values()))

    if not isinstance(title, str) or not title.strip():
        title = _fallback_title(source_text)

    data["title"] = _clean_title(title)

    ### Cards
    cards = data.get("cards", [])
    if not isinstance(cards, list):
        cards = []
    data["cards"] = cards

    return data
